name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model:
          - base: bigscience/bloom-560m
            adapter: artek0chumak/bloom-560m-safe-peft
          - base: Maykeye/TinyLLama-v0
            adapter: ~
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
      fail-fast: true
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: Key-v1-${{ matrix.python-version }}-${{ hashFiles('setup.cfg') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Test
        run: |
          export MODEL_NAME=${{ matrix.model.base }}
          export REF_NAME=${{ matrix.model.base }}
          export ADAPTER_NAME=${{ matrix.model.adapter }}

          python -m petals.cli.run_dht --identity tests/test.id --host_maddrs /ip4/127.0.0.1/tcp/31337 &> bootstrap.log &
          BOOTSTRAP_PID=$!

          export INITIAL_PEERS=/ip4/127.0.0.1/tcp/31337/p2p/QmS9KwZptnVdB9FFV7uGgaTq4sEKBwcYeKZDfSpyKDUd1g
          # ^-- multiaddr in INITIAL_PEERS is determined by --identity and --host_maddrs

          sleep 5  # wait for DHT init

          python -m petals.cli.run_server --converted_model_name_or_path $MODEL_NAME --num_blocks 3 \
            --initial_peers $INITIAL_PEERS --throughput 1 --torch_dtype float32 --adapters $ADAPTER_NAME \
            --mean_balance_check_period 10 &> server1.log &
          SERVER1_PID=$!
          # ^-- this server should choose blocks 0:3, then see that blocks 22:24 are not covered and move to 21:24

          sleep 10  # wait for the 1st server to choose blocks

          python -m petals.cli.run_server --converted_model_name_or_path $MODEL_NAME --block_indices 0:12 \
            --initial_peers $INITIAL_PEERS --throughput 1 --torch_dtype float32 --adapters $ADAPTER_NAME \
            --attn_cache_tokens 2048 --max_chunk_size_bytes 1024 &> server2.log &
          SERVER2_PID=$!

          python -m petals.cli.run_server --converted_model_name_or_path $MODEL_NAME --block_indices 12:22 \
            --initial_peers $INITIAL_PEERS --throughput 1 --torch_dtype float32 --adapters $ADAPTER_NAME &> server3.log &
          SERVER3_PID=$!

          python -m petals.cli.run_server --converted_model_name_or_path $MODEL_NAME --block_indices 11:13 \
            --initial_peers $INITIAL_PEERS --throughput eval --torch_dtype float32 --tensor_parallel_devices cpu cpu &> server4.log &
          SERVER4_PID=$!

          tail -n 100 -f bootstrap.log server*.log &
          LOGGER_PID=$!
          sleep 30  # wait for servers to eval throughput, download layers, and rebalance

          kill -0 $BOOTSTRAP_PID $SERVER1_PID $SERVER2_PID $SERVER3_PID $SERVER4_PID  # ensure all peers survived init

          pytest tests --durations=0 --durations-min=1.0 -v

          kill -0 BOOTSTRAP_PID $SERVER1_PID $SERVER2_PID $SERVER3_PID $SERVER4_PID  # ensure all peers survived tests

          kill -s SIGINT $BOOTSTRAP_PID $SERVER1_PID $SERVER2_PID $SERVER3_PID $SERVER4_PID $LOGGER_PID
          echo "Done!"
